    <div class="left">
      <a href="https://git.linux.iastate.edu/309Spring2017/GB_02_DegreeQuest">repository</a> |
      <a href="http://www.monogame.net">monogame</a> |
      <a href="https://dev.mysql.com/downloads/mysql/">mysql</a>
    </div>

    <div class="right">

      <span class="doNotDisplay">Related sites:
      | <a href="http://cat-v.org/update_log">site updates</a>
      | <a href="/sitemap">site map</a> |</span>

    <script type="text/javascript">var addthis_disable_flash = true; var addthis_pub="uriell";</script>
    <a href="http://www.addthis.com/bookmark.php?v=20" onmouseover="return addthis_open(this, '', '[URL]', '[TITLE]')" onmouseout="addthis_close()" onclick="return addthis_sendto()"><img src="http://s7.addthis.com/static/btn/lg-share-en.gif" width="125" height="16" alt="Bookmark and Share" style="border:0"/></a><script type="text/javascript" src="http://s7.addthis.com/js/200/addthis_widget.js"></script>
    </div>

