<div class="left">
	<a href="https://git.linux.iastate.edu/309Spring2017/GB_02_DegreeQuest">repository</a> |
	<a href="http://www.monogame.net">monogame</a> |
	<a href="https://dev.mysql.com/downloads/mysql/">mysql</a> |
	<a href="https://www.microsoft.com/en-us/download/details.aspx?id=48146">visual studio</a> |
	<a href="https://git.linux.iastate.edu/309Spring2017/GB_02_DegreeQuest.git">clone url</a>

</div>

<div class="right">

	<span class="doNotDisplay">Related sites:
	| <a href="http://cat-v.org/update_log">site updates</a>
	| <a href="/sitemap">site map</a> |</span>

</div>

